### ISSUE TITLE
[✨Enhancement] サイドバーコンポーネントの作成

### ISSUE THREAD

**Issue by hourensou26** [KTC-Security-Circle/SC-system-frontend#8]
## 解決したい問題
チャット画面につけるサイドバーが欲しい

## やってほしいこと
セッションの部分のみ多ければスクロールにするサイドバーを作る
UIのイメージはChatG P Tのサイドバー

**Comment by Kitagawa19** [comment]
Dockerfileとcompose.ymlを作成

**Comment by hourensou26** [comment]
ブランチ作った

**Comment by hourensou26** [comment]
セッションの・・・を押したときのpopoverとモバイル時の画面
![スクリーンショット 2024-11-27 212953](https://github.com/user-attachments/assets/e65ee6ce-e178-44b8-af2f-7e398d2f8197)
![スクリーンショット 2024-11-27 213040](https://github.com/user-attachments/assets/278b8b39-19bd-4cba-b830-8c235eedb93a)

**Comment by hourensou26** [comment]
見た目完成
